In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('Luxury_Housing_Bangalore.csv')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 63717 entries, 0 to 63716
Data columns (total 18 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Property_ID           63717 non-null  object
 1   Micro_Market          63717 non-null  object
 2   Project_Name          63717 non-null  object
 3   Developer_Name        63717 non-null  object
 4   Unit_Size_Sqft        57363 non-null  float64
 5   Configuration         63717 non-null  object
 6   Ticket_Price_Cr       57424 non-null  object
 7   Transaction_Type      63717 non-null  object
 8   Buyer_Type            63717 non-null  object
 9   Purchase_Quarter      63717 non-null  object
 10  Connectivity_Score    63717 non-null  float64
 11  Amenity_Score         57424 non-null  float64
 12  Possession_Status     63716 non-null  object
 13  Sales_Channel         63716 non-null  object
 14  NRI_Buyer             63716 non-null  object
 15  Locality_Infra_Score  63716 non-null  float64
 16  Avg_Traffic_Time_Min  63716 non-null  float64
 17  Buyer_Comments        52082 non-null  object
dtypes: float64(5), object(13)
memory usage: 8.8+ MB

In [4]:
df.isnull().sum()

Property_ID                 0
Micro_Market                0
Project_Name                0
Developer_Name              0
Unit_Size_Sqft           6354
Configuration               0
Ticket_Price_Cr          6293
Transaction_Type            0
Buyer_Type                  0
Purchase_Quarter            0
Connectivity_Score          0
Amenity_Score            6293
Possession_Status           1
Sales_Channel               1
NRI_Buyer                   1
Locality_Infra_Score        1
Avg_Traffic_Time_Min        1
Buyer_Comments          11635
dtype: int64

In [5]:
df['Developer_Name'] = df['Developer_Name'].str.lower()

In [7]:
df.head()

,Property_ID,Micro_Market,Project_Name,Developer_Name,Unit_Size_Sqft,Configuration,Ticket_Price_Cr,Transaction_Type,Buyer_Type,Purchase_Quarter,Connectivity_Score,Amenity_Score,Possession_Status,Sales_Channel,NRI_Buyer,Locality_Infra_Score,Avg_Traffic_Time_Min,Buyer_Comments
0,PROP000001,Sarjapur Road,Project_0,rmz,4025.0,4bhk,12.750846039118798,Primary,NRI,2025-03-31,7.990091,5.462863,Launch,Broker,yes,9.212491,18.0,Loved the amenities!
1,PROP000002,Indiranagar,Project_1,puravankara,5760.0,3Bhk,16.292151871065954,Primary,Other,2024-06-30,4.839024,NaN,Under construction,NRI Desk,no,7.723898,106.0,NaN
2,PROP000003,Bannerghatta Road,Project_2,tata housing,7707.0,4bhk,10.517724412961911,Primary,HNI,2023-12-31,8.131315,8.669227,Ready to move,Direct,yes,6.985493,113.0,Agent was not responsive.
3,PROP000004,bellary road,Project_3,embassy,6192.0,3BHK,9.396367494232896,Primary,HNI,2024-03-31,7.501657,5.720246,Ready to move,Online,yes,6.100929,106.0,Excellent location!
4,PROP000005,Koramangala,Project_4,snn raj,7147.0,4Bhk,15.345392444511946,Secondary,HNI,2024-12-31,4.525216,8.609649,Under construction,Broker,no,5.312510,18.0,Too far from my office.

In [8]:
df['Developer_Name'] = df['Developer_Name'].str.strip()

In [9]:
df['Developer_Name'] = df['Developer_Name'].str.replace(r'[^\w\s]', '', regex=True)

In [10]:
df.head()

,Property_ID,Micro_Market,Project_Name,Developer_Name,Unit_Size_Sqft,Configuration,Ticket_Price_Cr,Transaction_Type,Buyer_Type,Purchase_Quarter,Connectivity_Score,Amenity_Score,Possession_Status,Sales_Channel,NRI_Buyer,Locality_Infra_Score,Avg_Traffic_Time_Min,Buyer_Comments
0,PROP000001,Sarjapur Road,Project_0,rmz,4025.0,4bhk,12.750846039118798,Primary,NRI,2025-03-31,7.990091,5.462863,Launch,Broker,yes,9.212491,18.0,Loved the amenities!
1,PROP000002,Indiranagar,Project_1,puravankara,5760.0,3Bhk,16.292151871065954,Primary,Other,2024-06-30,4.839024,NaN,Under construction,NRI Desk,no,7.723898,106.0,NaN
2,PROP000003,Bannerghatta Road,Project_2,tata housing,7707.0,4bhk,10.517724412961911,Primary,HNI,2023-12-31,8.131315,8.669227,Ready to move,Direct,yes,6.985493,113.0,Agent was not responsive.
3,PROP000004,bellary road,Project_3,embassy,6192.0,3BHK,9.396367494232896,Primary,HNI,2024-03-31,7.501657,5.720246,Ready to move,Online,yes,6.100929,106.0,Excellent location!
4,PROP000005,Koramangala,Project_4,snn raj,7147.0,4Bhk,15.345392444511946,Secondary,HNI,2024-12-31,4.525216,8.609649,Under construction,Broker,no,5.312510,18.0,Too far from my office.

In [11]:
df['Configuration'] = df['Configuration'].str.lower().str.strip()

In [12]:
df['Configuration'] = df['Configuration'].str.replace(r'\s+', '', regex=True)

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 63717 entries, 0 to 63716
Data columns (total 18 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Property_ID           63717 non-null  object
 1   Micro_Market          63717 non-null  object
 2   Project_Name          63717 non-null  object
 3   Developer_Name        63717 non-null  object
 4   Unit_Size_Sqft        57363 non-null  float64
 5   Configuration         63717 non-null  object
 6   Ticket_Price_Cr       57424 non-null  object
 7   Transaction_Type      63717 non-null  object
 8   Buyer_Type            63717 non-null  object
 9   Purchase_Quarter      63717 non-null  object
 10  Connectivity_Score    63717 non-null  float64
 11  Amenity_Score         57424 non-null  float64
 12  Possession_Status     63716 non-null  object
 13  Sales_Channel         63716 non-null  object
 14  NRI_Buyer             63716 non-null  object
 15  Locality_Infra_Score  63716 non-null  float64
 16  Avg_Traffic_Time_Min  63716 non-null  float64
 17  Buyer_Comments        52082 non-null  object
dtypes: float64(5), object(13)
memory usage: 8.8+ MB

In [14]:
df['Ticket_Price_Cr'] = pd.to_numeric(df['Ticket_Price_Cr'], errors='coerce')

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 63717 entries, 0 to 63716
Data columns (total 18 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Property_ID           63717 non-null  object
 1   Micro_Market          63717 non-null  object
 2   Project_Name          63717 non-null  object
 3   Developer_Name        63717 non-null  object
 4   Unit_Size_Sqft        57363 non-null  float64
 5   Configuration         63717 non-null  object
 6   Ticket_Price_Cr       45886 non-null  float64
 7   Transaction_Type      63717 non-null  object
 8   Buyer_Type            63717 non-null  object
 9   Purchase_Quarter      63717 non-null  object
 10  Connectivity_Score    63717 non-null  float64
 11  Amenity_Score         57424 non-null  float64
 12  Possession_Status     63716 non-null  object
 13  Sales_Channel         63716 non-null  object
 14  NRI_Buyer             63716 non-null  object
 15  Locality_Infra_Score  63716 non-null  float64
 16  Avg_Traffic_Time_Min  63716 non-null  float64
 17  Buyer_Comments        52082 non-null  object
dtypes: float64(6), object(12)
memory usage: 8.8+ MB

In [16]:
df = df.drop(columns=['Buyer_Comments'])

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 63717 entries, 0 to 63716
Data columns (total 17 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Property_ID           63717 non-null  object
 1   Micro_Market          63717 non-null  object
 2   Project_Name          63717 non-null  object
 3   Developer_Name        63717 non-null  object
 4   Unit_Size_Sqft        57363 non-null  float64
 5   Configuration         63717 non-null  object
 6   Ticket_Price_Cr       45886 non-null  float64
 7   Transaction_Type      63717 non-null  object
 8   Buyer_Type            63717 non-null  object
 9   Purchase_Quarter      63717 non-null  object
 10  Connectivity_Score    63717 non-null  float64
 11  Amenity_Score         57424 non-null  float64
 12  Possession_Status     63716 non-null  object
 13  Sales_Channel         63716 non-null  object
 14  NRI_Buyer             63716 non-null  object
 15  Locality_Infra_Score  63716 non-null  float64
 16  Avg_Traffic_Time_Min  63716 non-null  float64
dtypes: float64(6), object(11)
memory usage: 8.3+ MB

In [18]:
df['Purchase_Quarter']

0        2025-03-31
1        2024-06-30
2        2023-12-31
3        2024-03-31
4        2024-12-31
            ...
63712    2024-09-30
63713    2024-03-31
63714    2025-03-31
63715    2023-09-30
63716    2023-12-31
Name: Purchase_Quarter, Length: 63717, dtype: object

In [19]:
df['Purchase_Quarter'] = pd.to_datetime(df['Purchase_Quarter'])

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 63717 entries, 0 to 63716
Data columns (total 17 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Property_ID           63717 non-null  object
 1   Micro_Market          63717 non-null  object
 2   Project_Name          63717 non-null  object
 3   Developer_Name        63717 non-null  object
 4   Unit_Size_Sqft        57363 non-null  float64
 5   Configuration         63717 non-null  object
 6   Ticket_Price_Cr       45886 non-null  float64
 7   Transaction_Type      63717 non-null  object
 8   Buyer_Type            63717 non-null  object
 9   Purchase_Quarter      63717 non-null  datetime64[ns]
 10  Connectivity_Score    63717 non-null  float64
 11  Amenity_Score         57424 non-null  float64
 12  Possession_Status     63716 non-null  object
 13  Sales_Channel         63716 non-null  object
 14  NRI_Buyer             63716 non-null  object
 15  Locality_Infra_Score  63716 non-null  float64
 16  Avg_Traffic_Time_Min  63716 non-null  float64
dtypes: datetime64[ns](1), float64(6), object(10)
memory usage: 8.3+ MB

In [21]:
df['Quarter_Number'] = df['Purchase_Quarter'].dt.quarter

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 63717 entries, 0 to 63716
Data columns (total 18 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Property_ID           63717 non-null  object
 1   Micro_Market          63717 non-null  object
 2   Project_Name          63717 non-null  object
 3   Developer_Name        63717 non-null  object
 4   Unit_Size_Sqft        57363 non-null  float64
 5   Configuration         63717 non-null  object
 6   Ticket_Price_Cr       45886 non-null  float64
 7   Transaction_Type      63717 non-null  object
 8   Buyer_Type            63717 non-null  object
 9   Purchase_Quarter      63717 non-null  datetime64[ns]
 10  Connectivity_Score    63717 non-null  float64
 11  Amenity_Score         57424 non-null  float64
 12  Possession_Status     63716 non-null  object
 13  Sales_Channel         63716 non-null  object
 14  NRI_Buyer             63716 non-null  object
 15  Locality_Infra_Score  63716 non-null  float64
 16  Avg_Traffic_Time_Min  63716 non-null  float64
 17  Quarter_Number        63717 non-null  int32
dtypes: datetime64[ns](1), float64(6), int32(1), object(10)
memory usage: 8.5+ MB

In [23]:
df.Quarter_Number

0        1
1        2
2        4
3        1
4        4
        ..
63712    3
63713    1
63714    1
63715    3
63716    4
Name: Quarter_Number, Length: 63717, dtype: int32

In [24]:
df['Ticket_Price_Cr'] = pd.to_numeric(df['Ticket_Price_Cr'], errors='coerce')

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 63717 entries, 0 to 63716
Data columns (total 18 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Property_ID           63717 non-null  object
 1   Micro_Market          63717 non-null  object
 2   Project_Name          63717 non-null  object
 3   Developer_Name        63717 non-null  object
 4   Unit_Size_Sqft        57363 non-null  float64
 5   Configuration         63717 non-null  object
 6   Ticket_Price_Cr       45886 non-null  float64
 7   Transaction_Type      63717 non-null  object
 8   Buyer_Type            63717 non-null  object
 9   Purchase_Quarter      63717 non-null  datetime64[ns]
 10  Connectivity_Score    63717 non-null  float64
 11  Amenity_Score         57424 non-null  float64
 12  Possession_Status     63716 non-null  object
 13  Sales_Channel         63716 non-null  object
 14  NRI_Buyer             63716 non-null  object
 15  Locality_Infra_Score  63716 non-null  float64
 16  Avg_Traffic_Time_Min  63716 non-null  float64
 17  Quarter_Number        63717 non-null  int32
dtypes: datetime64[ns](1), float64(6), int32(1), object(10)
memory usage: 8.5+ MB

In [27]:
df.isnull().sum()

Property_ID                 0
Micro_Market                0
Project_Name                0
Developer_Name              0
Unit_Size_Sqft           6354
Configuration               0
Ticket_Price_Cr         17831
Transaction_Type            0
Buyer_Type                  0
Purchase_Quarter            0
Connectivity_Score          0
Amenity_Score            6293
Possession_Status           1
Sales_Channel               1
NRI_Buyer                   1
Locality_Infra_Score        1
Avg_Traffic_Time_Min        1
Quarter_Number              0
dtype: int64

In [28]:
df['Unit_Size_Sqft'] = df.groupby(['Configuration'])['Unit_Size_Sqft']\
    .transform(lambda x: x.fillna(x.median()))

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 63717 entries, 0 to 63716
Data columns (total 18 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Property_ID           63717 non-null  object
 1   Micro_Market          63717 non-null  object
 2   Project_Name          63717 non-null  object
 3   Developer_Name        63717 non-null  object
 4   Unit_Size_Sqft        63717 non-null  float64
 5   Configuration         63717 non-null  object
 6   Ticket_Price_Cr       45886 non-null  float64
 7   Transaction_Type      63717 non-null  object
 8   Buyer_Type            63717 non-null  object
 9   Purchase_Quarter      63717 non-null  datetime64[ns]
 10  Connectivity_Score    63717 non-null  float64
 11  Amenity_Score         57424 non-null  float64
 12  Possession_Status     63716 non-null  object
 13  Sales_Channel         63716 non-null  object
 14  NRI_Buyer             63716 non-null  object
 15  Locality_Infra_Score  63716 non-null  float64
 16  Avg_Traffic_Time_Min  63716 non-null  float64
 17  Quarter_Number        63717 non-null  int32
dtypes: datetime64[ns](1), float64(6), int32(1), object(10)
memory usage: 8.5+ MB

In [32]:
df['Configuration'].value_counts()

Configuration
5bhk+    21374
3bhk     21262
4bhk     21081
Name: count, dtype: int64

In [33]:
df['BHK'] = df['Configuration'].str.extract(r'(\d+)').astype(int)

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 63717 entries, 0 to 63716
Data columns (total 19 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Property_ID           63717 non-null  object
 1   Micro_Market          63717 non-null  object
 2   Project_Name          63717 non-null  object
 3   Developer_Name        63717 non-null  object
 4   Unit_Size_Sqft        63717 non-null  float64
 5   Configuration         63717 non-null  object
 6   Ticket_Price_Cr       45886 non-null  float64
 7   Transaction_Type      63717 non-null  object
 8   Buyer_Type            63717 non-null  object
 9   Purchase_Quarter      63717 non-null  datetime64[ns]
 10  Connectivity_Score    63717 non-null  float64
 11  Amenity_Score         57424 non-null  float64
 12  Possession_Status     63716 non-null  object
 13  Sales_Channel         63716 non-null  object
 14  NRI_Buyer             63716 non-null  object
 15  Locality_Infra_Score  63716 non-null  float64
 16  Avg_Traffic_Time_Min  63716 non-null  float64
 17  Quarter_Number        63717 non-null  int32
 18  BHK                   63717 non-null  int64
dtypes: datetime64[ns](1), float64(6), int32(1), int64(1), object(10)
memory usage: 9.0+ MB

In [35]:
df.BHK

0        4
1        3
2        4
3        3
4        4
        ..
63712    5
63713    3
63714    5
63715    3
63716    5
Name: BHK, Length: 63717, dtype: int64

In [36]:
df = df.drop(columns=['Configuration'])

In [37]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 63717 entries, 0 to 63716
Data columns (total 18 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Property_ID           63717 non-null  object
 1   Micro_Market          63717 non-null  object
 2   Project_Name          63717 non-null  object
 3   Developer_Name        63717 non-null  object
 4   Unit_Size_Sqft        63717 non-null  float64
 5   Ticket_Price_Cr       45886 non-null  float64
 6   Transaction_Type      63717 non-null  object
 7   Buyer_Type            63717 non-null  object
 8   Purchase_Quarter      63717 non-null  datetime64[ns]
 9   Connectivity_Score    63717 non-null  float64
 10  Amenity_Score         57424 non-null  float64
 11  Possession_Status     63716 non-null  object
 12  Sales_Channel         63716 non-null  object
 13  NRI_Buyer             63716 non-null  object
 14  Locality_Infra_Score  63716 non-null  float64
 15  Avg_Traffic_Time_Min  63716 non-null  float64
 16  Quarter_Number        63717 non-null  int32
 17  BHK                   63717 non-null  int64
dtypes: datetime64[ns](1), float64(6), int32(1), int64(1), object(9)
memory usage: 8.5+ MB

In [38]:
df.Amenity_Score

0        5.462863
1             NaN
2        8.669227
3        5.720246
4        8.609649
           ...
63712    5.664818
63713    5.625323
63714    5.355570
63715    7.446287
63716         NaN
Name: Amenity_Score, Length: 63717, dtype: float64

In [39]:
df['Amenity_Score'].describe()

count    57424.000000
mean         7.509119
std          1.440236
min          5.000265
25%          6.267943
50%          7.508014
75%          8.757439
max          9.999659
Name: Amenity_Score, dtype: float64

In [40]:
df['Amenity_Score'] = df.groupby('Micro_Market')['Amenity_Score']\
    .transform(lambda x: x.fillna(x.median()))

In [41]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 63717 entries, 0 to 63716
Data columns (total 18 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Property_ID           63717 non-null  object
 1   Micro_Market          63717 non-null  object
 2   Project_Name          63717 non-null  object
 3   Developer_Name        63717 non-null  object
 4   Unit_Size_Sqft        63717 non-null  float64
 5   Ticket_Price_Cr       45886 non-null  float64
 6   Transaction_Type      63717 non-null  object
 7   Buyer_Type            63717 non-null  object
 8   Purchase_Quarter      63717 non-null  datetime64[ns]
 9   Connectivity_Score    63717 non-null  float64
 10  Amenity_Score         63717 non-null  float64
 11  Possession_Status     63716 non-null  object
 12  Sales_Channel         63716 non-null  object
 13  NRI_Buyer             63716 non-null  object
 14  Locality_Infra_Score  63716 non-null  float64
 15  Avg_Traffic_Time_Min  63716 non-null  float64
 16  Quarter_Number        63717 non-null  int32
 17  BHK                   63717 non-null  int64
dtypes: datetime64[ns](1), float64(6), int32(1), int64(1), object(9)
memory usage: 8.5+ MB

In [42]:
df.isnull().sum()

Property_ID                 0
Micro_Market                0
Project_Name                0
Developer_Name              0
Unit_Size_Sqft              0
Ticket_Price_Cr         17831
Transaction_Type            0
Buyer_Type                  0
Purchase_Quarter            0
Connectivity_Score          0
Amenity_Score               0
Possession_Status           1
Sales_Channel               1
NRI_Buyer                   1
Locality_Infra_Score        1
Avg_Traffic_Time_Min        1
Quarter_Number              0
BHK                         0
dtype: int64

In [43]:
df = df.dropna(subset=['Ticket_Price_Cr', 'Unit_Size_Sqft'])

In [44]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 45886 entries, 0 to 63716
Data columns (total 18 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Property_ID           45886 non-null  object
 1   Micro_Market          45886 non-null  object
 2   Project_Name          45886 non-null  object
 3   Developer_Name        45886 non-null  object
 4   Unit_Size_Sqft        45886 non-null  float64
 5   Ticket_Price_Cr       45886 non-null  float64
 6   Transaction_Type      45886 non-null  object
 7   Buyer_Type            45886 non-null  object
 8   Purchase_Quarter      45886 non-null  datetime64[ns]
 9   Connectivity_Score    45886 non-null  float64
 10  Amenity_Score         45886 non-null  float64
 11  Possession_Status     45885 non-null  object
 12  Sales_Channel         45885 non-null  object
 13  NRI_Buyer             45885 non-null  object
 14  Locality_Infra_Score  45885 non-null  float64
 15  Avg_Traffic_Time_Min  45885 non-null  float64
 16  Quarter_Number        45886 non-null  int32
 17  BHK                   45886 non-null  int64
dtypes: datetime64[ns](1), float64(6), int32(1), int64(1), object(9)
memory usage: 6.5+ MB

In [46]:
df.isnull().sum()

Property_ID             0
Micro_Market            0
Project_Name            0
Developer_Name          0
Unit_Size_Sqft          0
Ticket_Price_Cr         0
Transaction_Type        0
Buyer_Type              0
Purchase_Quarter        0
Connectivity_Score      0
Amenity_Score           0
Possession_Status       1
Sales_Channel           1
NRI_Buyer               1
Locality_Infra_Score    1
Avg_Traffic_Time_Min    1
Quarter_Number          0
BHK                     0
dtype: int64

In [47]:
df['Possession_Status'].fillna(df['Possession_Status'].mode()[0], inplace=True)
df['Sales_Channel'].fillna(df['Sales_Channel'].mode()[0], inplace=True)
df['NRI_Buyer'].fillna(df['NRI_Buyer'].mode()[0], inplace=True)

/tmp/ipykernel_6259/1390507731.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Possession_Status'].fillna(df['Possession_Status'].mode()[0], inplace=True)
/tmp/ipykernel_6259/1390507731.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Sales_Channel'].fillna(df['Sales_Channel'].mode()[0], inplace=True)
/tmp/ipykernel_6259/1390507731.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['NRI_Buyer'].fillna(df['NRI_Buyer'].mode()[0], inplace=True)

In [48]:
df['Locality_Infra_Score'].fillna(df['Locality_Infra_Score'].median(), inplace=True)
df['Avg_Traffic_Time_Min'].fillna(df['Avg_Traffic_Time_Min'].median(), inplace=True)

/tmp/ipykernel_6259/3991512247.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Locality_Infra_Score'].fillna(df['Locality_Infra_Score'].median(), inplace=True)
/tmp/ipykernel_6259/3991512247.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Avg_Traffic_Time_Min'].fillna(df['Avg_Traffic_Time_Min'].median(), inplace=True)

In [49]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 45886 entries, 0 to 63716
Data columns (total 18 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Property_ID           45886 non-null  object
 1   Micro_Market          45886 non-null  object
 2   Project_Name          45886 non-null  object
 3   Developer_Name        45886 non-null  object
 4   Unit_Size_Sqft        45886 non-null  float64
 5   Ticket_Price_Cr       45886 non-null  float64
 6   Transaction_Type      45886 non-null  object
 7   Buyer_Type            45886 non-null  object
 8   Purchase_Quarter      45886 non-null  datetime64[ns]
 9   Connectivity_Score    45886 non-null  float64
 10  Amenity_Score         45886 non-null  float64
 11  Possession_Status     45886 non-null  object
 12  Sales_Channel         45886 non-null  object
 13  NRI_Buyer             45886 non-null  object
 14  Locality_Infra_Score  45886 non-null  float64
 15  Avg_Traffic_Time_Min  45886 non-null  float64
 16  Quarter_Number        45886 non-null  int32
 17  BHK                   45886 non-null  int64
dtypes: datetime64[ns](1), float64(6), int32(1), int64(1), object(9)
memory usage: 6.5+ MB

In [50]:
df.isnull().sum()

Property_ID             0
Micro_Market            0
Project_Name            0
Developer_Name          0
Unit_Size_Sqft          0
Ticket_Price_Cr         0
Transaction_Type        0
Buyer_Type              0
Purchase_Quarter        0
Connectivity_Score      0
Amenity_Score           0
Possession_Status       0
Sales_Channel           0
NRI_Buyer               0
Locality_Infra_Score    0
Avg_Traffic_Time_Min    0
Quarter_Number          0
BHK                     0
dtype: int64

In [51]:
df[['Ticket_Price_Cr', 'Unit_Size_Sqft']].isnull().sum()

Ticket_Price_Cr    0
Unit_Size_Sqft     0
dtype: int64

In [52]:
df['Price_per_Sqft'] = (df['Ticket_Price_Cr'] * 1e7) / df['Unit_Size_Sqft']

In [53]:
df['Price_per_Sqft'].describe()

count    4.588600e+04
mean    -6.151959e+05
std      1.029587e+07
min     -1.000000e+09
25%      1.547785e+04
50%      2.000823e+04
75%      2.666160e+04
max      3.207184e+05
Name: Price_per_Sqft, dtype: float64

In [54]:
df[df['Ticket_Price_Cr'] <= 0]

,Property_ID,Micro_Market,Project_Name,Developer_Name,Unit_Size_Sqft,Ticket_Price_Cr,Transaction_Type,Buyer_Type,Purchase_Quarter,Connectivity_Score,Amenity_Score,Possession_Status,Sales_Channel,NRI_Buyer,Locality_Infra_Score,Avg_Traffic_Time_Min,Quarter_Number,BHK,Price_per_Sqft
3645,PROP003646,INDIRANAGAR,Project_145,embassy,5092.0,-0.391623,Primary,Startup Founder,2024-06-30,7.149634,6.123946,Under construction,Direct,no,6.967136,105.0,2,4,-769.093841
39358,PROP039359,Hebbal,Project_358,tata housing,4924.0,-0.287197,Primary,NRI,2023-09-30,4.167448,7.430698,Ready to move,NRI Desk,yes,8.249373,115.0,3,5,-583.260311
50185,PROP050186,jp nagar,Project_185,godrej,5807.0,-0.193873,Primary,CXO,2024-12-31,5.707500,9.986799,Launch,Broker,no,7.867063,73.0,4,5,-333.860845

In [58]:
df = df[df['Ticket_Price_Cr'] > 0]

In [59]:
df['Price_per_Sqft'] = (df['Ticket_Price_Cr'] * 1e7) / df['Unit_Size_Sqft']

In [60]:
df['Price_per_Sqft'].describe()

count    4.588300e+04
mean    -6.152361e+05
std      1.029621e+07
min     -1.000000e+09
25%      1.547825e+04
50%      2.000867e+04
75%      2.666200e+04
max      3.207184e+05
Name: Price_per_Sqft, dtype: float64

In [61]:
df[df['Ticket_Price_Cr'] <= 0]

Empty DataFrame
Columns: [Property_ID, Micro_Market, Project_Name, Developer_Name, Unit_Size_Sqft, Ticket_Price_Cr, Transaction_Type, Buyer_Type, Purchase_Quarter, Connectivity_Score, Amenity_Score, Possession_Status, Sales_Channel, NRI_Buyer, Locality_Infra_Score, Avg_Traffic_Time_Min, Quarter_Number, BHK, Price_per_Sqft]
Index: []

In [62]:
df[df['Price_per_Sqft'] < 0]

,Property_ID,Micro_Market,Project_Name,Developer_Name,Unit_Size_Sqft,Ticket_Price_Cr,Transaction_Type,Buyer_Type,Purchase_Quarter,Connectivity_Score,Amenity_Score,Possession_Status,Sales_Channel,NRI_Buyer,Locality_Infra_Score,Avg_Traffic_Time_Min,Quarter_Number,BHK,Price_per_Sqft
145,PROP000146,bellary road,Project_145,puravankara,-1.0,9.094891,Secondary,Startup Founder,2024-03-31,9.952351,7.824742,Ready to move,Direct,yes,6.690428,78.0,1,3,-9.094891e+07
238,PROP000239,KORAMANGALA,Project_238,sobha,-1.0,11.065758,Secondary,Other,2024-06-30,8.900902,7.491866,Ready to move,Broker,yes,5.698885,43.0,2,5,-1.106576e+08
244,PROP000245,sarjapur road,Project_244,lt realty,-1.0,18.426594,Secondary,Startup Founder,2023-09-30,5.045976,7.885277,Under construction,Online,yes,5.766082,102.0,3,5,-1.842659e+08
289,PROP000290,Yelahanka,Project_289,sobha,-1.0,12.199936,Secondary,CXO,2024-06-30,7.194905,6.825103,Ready to move,NRI Desk,no,9.728299,21.0,2,4,-1.219994e+08
747,PROP000748,sarjapur road,Project_247,embassy,-1.0,9.448331,Primary,Other,2023-12-31,8.701167,5.982552,Ready to move,Online,yes,8.384907,57.0,4,3,-9.448331e+07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62514,PROP062515,WHITEFIELD,Project_14,embassy,-1.0,7.233131,Secondary,Other,2024-12-31,5.394972,6.091488,Ready to move,Online,no,8.310403,119.0,4,4,-7.233131e+07
62599,PROP062600,SARJAPUR ROAD,Project_99,total environment,-1.0,14.266873,Primary,CXO,2023-12-31,4.597224,7.612972,Launch,Direct,yes,9.728670,117.0,4,5,-1.426687e+08
63016,PROP063017,hennur road,Project_16,tata housing,-1.0,9.978117,Secondary,Other,2024-12-31,5.197454,5.755862,Ready to move,Online,yes,9.694200,94.0,4,5,-9.978117e+07
63084,PROP063085,rajajinagar,Project_84,snn raj,-1.0,8.571764,Primary,Other,2025-03-31,6.480746,8.671789,Under construction,Direct,no,6.772088,94.0,1,4,-8.571764e+07
63514,PROP063515,Mg Road,Project_14,sobha,-1.0,17.607280,Primary,Other,2023-09-30,8.970470,8.794869,Under construction,Broker,yes,9.275476,26.0,3,3,-1.760728e+08

In [63]:
df['Unit_Size_Sqft'].describe()

count    45883.000000
mean      5974.458710
std       1690.294923
min         -1.000000
25%       4660.000000
50%       5986.000000
75%       7327.000000
max       8999.000000
Name: Unit_Size_Sqft, dtype: float64

In [65]:
import numpy as np
df['Unit_Size_Sqft'] = df['Unit_Size_Sqft'].replace(-1, np.nan)

In [66]:
df = df.dropna(subset=['Unit_Size_Sqft'])

In [67]:
df['Price_per_Sqft'] = (df['Ticket_Price_Cr'] * 1e7) / df['Unit_Size_Sqft']

In [68]:
df['Price_per_Sqft'].describe()

count     45649.000000
mean      23096.865702
std       16195.861583
min        1181.384845
25%       15553.025813
50%       20060.907786
75%       26718.813779
max      320718.409237
Name: Price_per_Sqft, dtype: float64

In [69]:
df.corr(numeric_only=True)['Price_per_Sqft'].sort_values(ascending=False)

Price_per_Sqft          1.000000
Ticket_Price_Cr         0.858664
Quarter_Number          0.005848
BHK                     0.004972
Amenity_Score           0.002056
Avg_Traffic_Time_Min   -0.001184
Locality_Infra_Score   -0.002477
Connectivity_Score     -0.006034
Unit_Size_Sqft         -0.419512
Name: Price_per_Sqft, dtype: float64

In [70]:
df['Transaction_Type'].value_counts()

Transaction_Type
Secondary    22857
Primary      22792
Name: count, dtype: int64

In [71]:
df['Booking_Flag'] = df['Transaction_Type'].map({
    'Primary': 1,
    'Secondary': 0
})

In [72]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 45649 entries, 0 to 63716
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Property_ID           45649 non-null  object
 1   Micro_Market          45649 non-null  object
 2   Project_Name          45649 non-null  object
 3   Developer_Name        45649 non-null  object
 4   Unit_Size_Sqft        45649 non-null  float64
 5   Ticket_Price_Cr       45649 non-null  float64
 6   Transaction_Type      45649 non-null  object
 7   Buyer_Type            45649 non-null  object
 8   Purchase_Quarter      45649 non-null  datetime64[ns]
 9   Connectivity_Score    45649 non-null  float64
 10  Amenity_Score         45649 non-null  float64
 11  Possession_Status     45649 non-null  object
 12  Sales_Channel         45649 non-null  object
 13  NRI_Buyer             45649 non-null  object
 14  Locality_Infra_Score  45649 non-null  float64
 15  Avg_Traffic_Time_Min  45649 non-null  float64
 16  Quarter_Number        45649 non-null  int32
 17  BHK                   45649 non-null  int64
 18  Price_per_Sqft        45649 non-null  float64
 19  Booking_Flag          45649 non-null  int64
dtypes: datetime64[ns](1), float64(7), int32(1), int64(2), object(9)
memory usage: 7.1+ MB

In [73]:
df.groupby('Booking_Flag')['Price_per_Sqft'].mean()

Booking_Flag
0    23014.524253
1    23179.441980
Name: Price_per_Sqft, dtype: float64

In [74]:
df['Developer_Name'].unique()

array(['rmz', 'puravankara', 'tata housing', 'embassy', 'snn raj',
       'prestige', 'total environment', 'godrej', 'brigade', 'lt realty',
       'sobha'], dtype=object)

In [75]:
df['Developer_Name'].nunique()

11

In [76]:
df['Developer_Name'].value_counts()

Developer_Name
prestige             4238
snn raj              4222
lt realty            4199
puravankara          4172
godrej               4163
total environment    4158
brigade              4128
embassy              4107
rmz                  4105
sobha                4083
tata housing         4074
Name: count, dtype: int64

In [77]:
df['Micro_Market'].unique()

array(['Sarjapur Road', 'Indiranagar', 'Bannerghatta Road',
       'bellary road', 'Koramangala', 'whitefield', 'sarjapur road',
       'JP NAGAR', 'Rajajinagar', 'koramangala', 'YELAHANKA',
       'WHITEFIELD', 'indiranagar', 'jayanagar', 'DOMLUR', 'HENNUR ROAD',
       'Domlur', 'Electronic City', 'Mg Road', 'Hebbal', 'mg road',
       'jp nagar', 'Jayanagar', 'BANNERGHATTA ROAD', 'MG ROAD',
       'KANAKAPURA ROAD', 'BELLARY ROAD', 'ELECTRONIC CITY',
       'Bellary Road', 'Hennur Road', 'rajajinagar', 'electronic city',
       'Kanakapura Road', 'INDIRANAGAR', 'hennur road', 'kanakapura road',
       'bannerghatta road', 'HEBBAL', 'domlur', 'Whitefield', 'yelahanka',
       'Yelahanka', 'hebbal', 'RAJAJINAGAR', 'SARJAPUR ROAD',
       'KORAMANGALA', 'Jp Nagar', 'JAYANAGAR'], dtype=object)

In [78]:
df['Micro_Market'].value_counts()

Micro_Market
mg road              995
Bannerghatta Road    992
Electronic City      991
electronic city      983
Jp Nagar             983
WHITEFIELD           982
jayanagar            981
JAYANAGAR            980
BANNERGHATTA ROAD    979
indiranagar          979
bannerghatta road    978
bellary road         976
jp nagar             974
sarjapur road        967
BELLARY ROAD         966
Kanakapura Road      965
ELECTRONIC CITY      965
JP NAGAR             961
Bellary Road         960
Sarjapur Road        958
Jayanagar            956
SARJAPUR ROAD        956
Hebbal               952
HEBBAL               951
KORAMANGALA          950
hebbal               948
MG ROAD              946
Yelahanka            945
yelahanka            944
kanakapura road      944
domlur               943
hennur road          942
whitefield           940
Hennur Road          933
rajajinagar          933
RAJAJINAGAR          933
koramangala          933
Whitefield           932
INDIRANAGAR          929
Mg Road              925
Rajajinagar          924
HENNUR ROAD          922
Indiranagar          921
Koramangala          916
Domlur               912
DOMLUR               909
KANAKAPURA ROAD      904
YELAHANKA            891
Name: count, dtype: int64

In [79]:
df['Micro_Market'] = (
    df['Micro_Market']
    .str.lower()
    .str.strip()
    .str.replace(r'\s+', ' ', regex=True)
)

In [80]:
df['Micro_Market'] = df['Micro_Market'].str.replace(r'[^\w\s]', '', regex=True)

In [81]:
df['Micro_Market'] = df['Micro_Market'].replace({
    'rd': 'road',
    'st': 'street',
    'nagar': 'nagar',
    'layout': 'layout'
}, regex=True)

In [82]:
df['Micro_Market'].value_counts().head(20)

Micro_Market
bannerghatta road    2949
electronic city      2939
jp nagar             2918
jayanagar            2917
bellary road         2902
sarjapur road        2881
mg road              2866
whitefield           2854
hebbal               2851
indiranagar          2829
kanakapura road      2813
koramangala          2799
hennur road          2797
rajajinagar          2790
yelahanka            2780
domlur               2764
Name: count, dtype: int64

In [85]:
df['Micro_Market'].value_counts()

Micro_Market
bannerghatta road    2949
electronic city      2939
jp nagar             2918
jayanagar            2917
bellary road         2902
sarjapur road        2881
mg road              2866
whitefield           2854
hebbal               2851
indiranagar          2829
kanakapura road      2813
koramangala          2799
hennur road          2797
rajajinagar          2790
yelahanka            2780
domlur               2764
Name: count, dtype: int64

In [86]:
df['Buyer_Type'].value_counts()

Buyer_Type
CXO                9211
NRI                9184
Other              9180
Startup Founder    9147
HNI                8927
Name: count, dtype: int64

In [87]:
df['Buyer_Type'] = (
    df['Buyer_Type']
    .str.lower()
    .str.strip()
)

In [88]:
df['Buyer_Type'] = df['Buyer_Type'].replace({
    'cxo': 'executive',
    'hni': 'high net worth',
    'startup founder': 'entrepreneur'
})

In [89]:
df.groupby('Buyer_Type')['Price_per_Sqft'].mean().sort_values()

Buyer_Type
executive         23018.844555
nri               23050.762483
high net worth    23059.250250
other             23177.121165
entrepreneur      23177.888197
Name: Price_per_Sqft, dtype: float64

In [90]:
df['Buyer_Type'].value_counts()

Buyer_Type
executive         9211
nri               9184
other             9180
entrepreneur      9147
high net worth    8927
Name: count, dtype: int64

In [91]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 45649 entries, 0 to 63716
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Property_ID           45649 non-null  object
 1   Micro_Market          45649 non-null  object
 2   Project_Name          45649 non-null  object
 3   Developer_Name        45649 non-null  object
 4   Unit_Size_Sqft        45649 non-null  float64
 5   Ticket_Price_Cr       45649 non-null  float64
 6   Transaction_Type      45649 non-null  object
 7   Buyer_Type            45649 non-null  object
 8   Purchase_Quarter      45649 non-null  datetime64[ns]
 9   Connectivity_Score    45649 non-null  float64
 10  Amenity_Score         45649 non-null  float64
 11  Possession_Status     45649 non-null  object
 12  Sales_Channel         45649 non-null  object
 13  NRI_Buyer             45649 non-null  object
 14  Locality_Infra_Score  45649 non-null  float64
 15  Avg_Traffic_Time_Min  45649 non-null  float64
 16  Quarter_Number        45649 non-null  int32
 17  BHK                   45649 non-null  int64
 18  Price_per_Sqft        45649 non-null  float64
 19  Booking_Flag          45649 non-null  int64
dtypes: datetime64[ns](1), float64(7), int32(1), int64(2), object(9)
memory usage: 7.1+ MB

In [93]:
df['Booking_Status'] = df['Transaction_Type'].apply(
    lambda x: 'Booked' if x == 'Primary' else 'Not Booked'
)

In [94]:
df['Booking_Status'].value_counts()

Booking_Status
Not Booked    22857
Booked        22792
Name: count, dtype: int64

In [95]:
booked_count = df[df['Booking_Status'] == 'Booked'].shape[0]

In [96]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 45649 entries, 0 to 63716
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Property_ID           45649 non-null  object
 1   Micro_Market          45649 non-null  object
 2   Project_Name          45649 non-null  object
 3   Developer_Name        45649 non-null  object
 4   Unit_Size_Sqft        45649 non-null  float64
 5   Ticket_Price_Cr       45649 non-null  float64
 6   Transaction_Type      45649 non-null  object
 7   Buyer_Type            45649 non-null  object
 8   Purchase_Quarter      45649 non-null  datetime64[ns]
 9   Connectivity_Score    45649 non-null  float64
 10  Amenity_Score         45649 non-null  float64
 11  Possession_Status     45649 non-null  object
 12  Sales_Channel         45649 non-null  object
 13  NRI_Buyer             45649 non-null  object
 14  Locality_Infra_Score  45649 non-null  float64
 15  Avg_Traffic_Time_Min  45649 non-null  float64
 16  Quarter_Number        45649 non-null  int32
 17  BHK                   45649 non-null  int64
 18  Price_per_Sqft        45649 non-null  float64
 19  Booking_Flag          45649 non-null  int64
 20  Booking_Status        45649 non-null  object
dtypes: datetime64[ns](1), float64(7), int32(1), int64(2), object(10)
memory usage: 7.5+ MB

In [98]:
booking_count = len(df)

In [99]:
booking_conversion_rate = booked_count / booking_count

In [100]:
print("Total:", booking_count)
print("Booked:", booked_count)
print("Conversion Rate:", booking_conversion_rate)

Total: 45649
Booked: 22792
Conversion Rate: 0.49928804574032287

In [101]:
conversion_by_market = df.groupby('Micro_Market').apply(
    lambda x: (x['Booking_Status'] == 'Booked').mean()
).reset_index(name='Booking_Conversion_Rate')

/tmp/ipykernel_6259/3869310969.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  conversion_by_market = df.groupby('Micro_Market').apply(

In [102]:
trend = df.groupby(['Purchase_Quarter', 'Micro_Market']).size().reset_index(name='Booking_Count')

In [103]:
builder_perf = df.groupby('Developer_Name').agg({
    'Ticket_Price_Cr': ['sum', 'mean']
}).reset_index()

builder_perf.columns = ['Developer_Name', 'Total_Revenue', 'Avg_Ticket']

In [104]:
sales_channel = df.groupby(['Sales_Channel', 'Booking_Status']).size().unstack(fill_value=0)

In [105]:
config_demand = df['BHK'].value_counts().reset_index()
config_demand.columns = ['BHK', 'Booking_Count']

In [106]:
df.isnull().sum()

Property_ID             0
Micro_Market            0
Project_Name            0
Developer_Name          0
Unit_Size_Sqft          0
Ticket_Price_Cr         0
Transaction_Type        0
Buyer_Type              0
Purchase_Quarter        0
Connectivity_Score      0
Amenity_Score           0
Possession_Status       0
Sales_Channel           0
NRI_Buyer               0
Locality_Infra_Score    0
Avg_Traffic_Time_Min    0
Quarter_Number          0
BHK                     0
Price_per_Sqft          0
Booking_Flag            0
Booking_Status          0
dtype: int64

In [107]:
df[df['Ticket_Price_Cr'] <= 0]

Empty DataFrame
Columns: [Property_ID, Micro_Market, Project_Name, Developer_Name, Unit_Size_Sqft, Ticket_Price_Cr, Transaction_Type, Buyer_Type, Purchase_Quarter, Connectivity_Score, Amenity_Score, Possession_Status, Sales_Channel, NRI_Buyer, Locality_Infra_Score, Avg_Traffic_Time_Min, Quarter_Number, BHK, Price_per_Sqft, Booking_Flag, Booking_Status]
Index: []

[0 rows x 21 columns]

In [108]:
df[df['Unit_Size_Sqft'] <= 0]

Empty DataFrame
Columns: [Property_ID, Micro_Market, Project_Name, Developer_Name, Unit_Size_Sqft, Ticket_Price_Cr, Transaction_Type, Buyer_Type, Purchase_Quarter, Connectivity_Score, Amenity_Score, Possession_Status, Sales_Channel, NRI_Buyer, Locality_Infra_Score, Avg_Traffic_Time_Min, Quarter_Number, BHK, Price_per_Sqft, Booking_Flag, Booking_Status]
Index: []

[0 rows x 21 columns]

In [109]:
df[df['Price_per_Sqft'] <= 0]

Empty DataFrame
Columns: [Property_ID, Micro_Market, Project_Name, Developer_Name, Unit_Size_Sqft, Ticket_Price_Cr, Transaction_Type, Buyer_Type, Purchase_Quarter, Connectivity_Score, Amenity_Score, Possession_Status, Sales_Channel, NRI_Buyer, Locality_Infra_Score, Avg_Traffic_Time_Min, Quarter_Number, BHK, Price_per_Sqft, Booking_Flag, Booking_Status]
Index: []

[0 rows x 21 columns]

In [110]:
df[['Ticket_Price_Cr', 'Unit_Size_Sqft', 'Price_per_Sqft']].describe()

       Ticket_Price_Cr  Unit_Size_Sqft  Price_per_Sqft
count     45649.000000    45649.000000    45649.000000
mean         12.756004     6005.089334    23096.865702
std           7.767527     1639.441562    16195.861583
min           0.776524     3000.000000     1181.384845
25%          10.025175     4687.000000    15553.025813
50%          12.053247     5986.000000    20060.907786
75%          14.105617     7334.000000    26718.813779
max         100.000000     8999.000000   320718.409237

In [111]:
Q1 = df['Price_per_Sqft'].quantile(0.25)
Q3 = df['Price_per_Sqft'].quantile(0.75)
IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

print(lower_bound, upper_bound)

-1195.656136826734 43467.49572875105

In [112]:
outliers = df[(df['Price_per_Sqft'] < lower_bound) | (df['Price_per_Sqft'] > upper_bound)]

print("Outliers count:", len(outliers))

Outliers count: 1659

In [113]:
df['Price_per_Sqft'] = df['Price_per_Sqft'].clip(upper=upper_bound)

In [114]:
df['Price_per_Sqft'].describe()

count    45649.000000
mean     21893.478045
std       8707.913885
min       1181.384845
25%      15553.025813
50%      20060.907786
75%      26718.813779
max      43467.495729
Name: Price_per_Sqft, dtype: float64

In [115]:
df[df['Price_per_Sqft'] > upper_bound]['Micro_Market'].value_counts()

Series([], Name: count, dtype: int64)

In [117]:
df.duplicated().sum()

np.int64(0)

In [118]:
df.isnull().sum().sum() == 0 and (df[['Ticket_Price_Cr','Unit_Size_Sqft','Price_per_Sqft']] > 0).all().all() and df.duplicated().sum() == 0

np.True_

In [121]:
df['Price_per_Sqft'] = (df['Ticket_Price_Cr'] * 1e7) / df['Unit_Size_Sqft']

In [122]:
df['Price_per_Sqft'].describe()

count     45649.000000
mean      23096.865702
std       16195.861583
min        1181.384845
25%       15553.025813
50%       20060.907786
75%       26718.813779
max      320718.409237
Name: Price_per_Sqft, dtype: float64

In [123]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 45649 entries, 0 to 63716
Data columns (total 22 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Property_ID           45649 non-null  object
 1   Micro_Market          45649 non-null  object
 2   Project_Name          45649 non-null  object
 3   Developer_Name        45649 non-null  object
 4   Unit_Size_Sqft        45649 non-null  float64
 5   Ticket_Price_Cr       45649 non-null  float64
 6   Transaction_Type      45649 non-null  object
 7   Buyer_Type            45649 non-null  object
 8   Purchase_Quarter      45649 non-null  datetime64[ns]
 9   Connectivity_Score    45649 non-null  float64
 10  Amenity_Score         45649 non-null  float64
 11  Possession_Status     45649 non-null  object
 12  Sales_Channel         45649 non-null  object
 13  NRI_Buyer             45649 non-null  object
 14  Locality_Infra_Score  45649 non-null  float64
 15  Avg_Traffic_Time_Min  45649 non-null  float64
 16  Quarter_Number        45649 non-null  int32
 17  BHK                   45649 non-null  int64
 18  Price_per_Sqft        45649 non-null  float64
 19  Booking_Flag          45649 non-null  int64
 20  Booking_Status        45649 non-null  object
 21  Price_per_Sqft_Log    45649 non-null  float64
dtypes: datetime64[ns](1), float64(8), int32(1), int64(2), object(10)
memory usage: 7.8+ MB

In [124]:
for col in df.select_dtypes(include='object'):
    print(f"\n🔹 {col}")
    print(df[col].unique())

🔹 Property_ID
['PROP000001' 'PROP000002' 'PROP000003' ... 'PROP063715' 'PROP063716'
 'PROP063717']

🔹 Micro_Market
['sarjapur road' 'indiranagar' 'bannerghatta road' 'bellary road'
 'koramangala' 'whitefield' 'jp nagar' 'rajajinagar' 'yelahanka'
 'jayanagar' 'domlur' 'hennur road' 'electronic city' 'mg road' 'hebbal'
 'kanakapura road']

🔹 Project_Name
['Project_0' 'Project_1' 'Project_2' 'Project_3' 'Project_4' 'Project_6'
 'Project_7' 'Project_8' 'Project_9' 'Project_10' 'Project_11'
 'Project_12' 'Project_13' 'Project_14' 'Project_15' 'Project_16'
 'Project_17' 'Project_18' 'Project_19' 'Project_20' 'Project_22'
 'Project_25' 'Project_27' 'Project_28' 'Project_29' 'Project_30'
 'Project_31' 'Project_32' 'Project_33' 'Project_34' 'Project_35'
 'Project_36' 'Project_37' 'Project_41' 'Project_42' 'Project_44'
 'Project_45' 'Project_46' 'Project_47' 'Project_49' 'Project_50'
 'Project_52' 'Project_54' 'Project_55' 'Project_56' 'Project_57'
 'Project_58' 'Project_59' 'Project_60' 'Project_61' 'Project_63'
 'Project_65' 'Project_66' 'Project_67' 'Project_68' 'Project_69'
 'Project_70' 'Project_71' 'Project_72' 'Project_73' 'Project_74'
 'Project_76' 'Project_77' 'Project_78' 'Project_79' 'Project_81'
 'Project_82' 'Project_83' 'Project_84' 'Project_86' 'Project_87'
 'Project_88' 'Project_89' 'Project_91' 'Project_92' 'Project_93'
 'Project_95' 'Project_96' 'Project_97' 'Project_98' 'Project_99'
 'Project_100' 'Project_101' 'Project_102' 'Project_103' 'Project_104'
 'Project_105' 'Project_106' 'Project_108' 'Project_109' 'Project_110'
 'Project_111' 'Project_112' 'Project_115' 'Project_116' 'Project_117'
 'Project_119' 'Project_120' 'Project_121' 'Project_122' 'Project_123'
 'Project_124' 'Project_125' 'Project_127' 'Project_128' 'Project_130'
 'Project_132' 'Project_133' 'Project_135' 'Project_137' 'Project_138'
 'Project_139' 'Project_140' 'Project_141' 'Project_142' 'Project_144'
 'Project_147' 'Project_150' 'Project_151' 'Project_153' 'Project_155'
 'Project_156' 'Project_157' 'Project_158' 'Project_159' 'Project_161'
 'Project_163' 'Project_165' 'Project_167' 'Project_168' 'Project_169'
 'Project_170' 'Project_174' 'Project_176' 'Project_177' 'Project_178'
 'Project_180' 'Project_181' 'Project_184' 'Project_185' 'Project_187'
 'Project_188' 'Project_189' 'Project_191' 'Project_192' 'Project_193'
 'Project_195' 'Project_196' 'Project_198' 'Project_200' 'Project_201'
 'Project_202' 'Project_204' 'Project_205' 'Project_206' 'Project_208'
 'Project_209' 'Project_210' 'Project_211' 'Project_212' 'Project_213'
 'Project_214' 'Project_215' 'Project_217' 'Project_219' 'Project_220'
 'Project_222' 'Project_224' 'Project_225' 'Project_226' 'Project_227'
 'Project_228' 'Project_229' 'Project_230' 'Project_231' 'Project_233'
 'Project_234' 'Project_236' 'Project_237' 'Project_239' 'Project_240'
 'Project_241' 'Project_242' 'Project_243' 'Project_245' 'Project_246'
 'Project_248' 'Project_249' 'Project_250' 'Project_251' 'Project_253'
 'Project_255' 'Project_256' 'Project_257' 'Project_259' 'Project_260'
 'Project_261' 'Project_262' 'Project_263' 'Project_264' 'Project_265'
 'Project_266' 'Project_268' 'Project_269' 'Project_270' 'Project_275'
 'Project_276' 'Project_277' 'Project_278' 'Project_280' 'Project_282'
 'Project_284' 'Project_286' 'Project_290' 'Project_291' 'Project_292'
 'Project_293' 'Project_294' 'Project_295' 'Project_296' 'Project_297'
 'Project_298' 'Project_300' 'Project_301' 'Project_302' 'Project_304'
 'Project_306' 'Project_308' 'Project_309' 'Project_310' 'Project_314'
 'Project_315' 'Project_317' 'Project_318' 'Project_319' 'Project_321'
 'Project_322' 'Project_323' 'Project_325' 'Project_326' 'Project_327'
 'Project_329' 'Project_330' 'Project_331' 'Project_332' 'Project_334'
 'Project_336' 'Project_337' 'Project_338' 'Project_339' 'Project_340'
 'Project_341' 'Project_342' 'Project_343' 'Project_344' 'Project_345'
 'Project_347' 'Project_348' 'Project_349' 'Project_350' 'Project_352'
 'Project_354' 'Project_355' 'Project_357' 'Project_358' 'Project_359'
 'Project_360' 'Project_362' 'Project_363' 'Project_366' 'Project_367'
 'Project_368' 'Project_370' 'Project_372' 'Project_373' 'Project_374'
 'Project_375' 'Project_376' 'Project_377' 'Project_381' 'Project_382'
 'Project_383' 'Project_384' 'Project_385' 'Project_386' 'Project_387'
 'Project_388' 'Project_389' 'Project_390' 'Project_394' 'Project_395'
 'Project_396' 'Project_397' 'Project_399' 'Project_401' 'Project_402'
 'Project_403' 'Project_404' 'Project_405' 'Project_407' 'Project_411'
 'Project_413' 'Project_414' 'Project_415' 'Project_417' 'Project_418'
 'Project_421' 'Project_422' 'Project_423' 'Project_424' 'Project_426'
 'Project_427' 'Project_428' 'Project_430' 'Project_431' 'Project_432'
 'Project_433' 'Project_434' 'Project_436' 'Project_437' 'Project_439'
 'Project_441' 'Project_442' 'Project_443' 'Project_444' 'Project_445'
 'Project_446' 'Project_447' 'Project_448' 'Project_449' 'Project_452'
 'Project_453' 'Project_454' 'Project_455' 'Project_456' 'Project_457'
 'Project_458' 'Project_460' 'Project_463' 'Project_464' 'Project_465'
 'Project_466' 'Project_467' 'Project_469' 'Project_470' 'Project_471'
 'Project_472' 'Project_474' 'Project_475' 'Project_476' 'Project_477'
 'Project_480' 'Project_481' 'Project_483' 'Project_484' 'Project_485'
 'Project_486' 'Project_487' 'Project_488' 'Project_490' 'Project_491'
 'Project_492' 'Project_493' 'Project_494' 'Project_495' 'Project_496'
 'Project_497' 'Project_498' 'Project_499' 'Project_5' 'Project_21'
 'Project_23' 'Project_26' 'Project_38' 'Project_40' 'Project_43'
 'Project_48' 'Project_51' 'Project_75' 'Project_80' 'Project_85'
 'Project_90' 'Project_94' 'Project_107' 'Project_113' 'Project_114'
 'Project_126' 'Project_129' 'Project_134' 'Project_136' 'Project_143'
 'Project_145' 'Project_146' 'Project_149' 'Project_152' 'Project_154'
 'Project_160' 'Project_164' 'Project_166' 'Project_171' 'Project_173'
 'Project_175' 'Project_182' 'Project_183' 'Project_186' 'Project_194'
 'Project_197' 'Project_203' 'Project_216' 'Project_221' 'Project_223'
 'Project_232' 'Project_235' 'Project_238' 'Project_244' 'Project_254'
 'Project_258' 'Project_272' 'Project_274' 'Project_281' 'Project_285'
 'Project_287' 'Project_289' 'Project_299' 'Project_303' 'Project_305'
 'Project_311' 'Project_316' 'Project_320' 'Project_328' 'Project_333'
 'Project_335' 'Project_346' 'Project_351' 'Project_356' 'Project_361'
 'Project_364' 'Project_365' 'Project_371' 'Project_378' 'Project_379'
 'Project_380' 'Project_391' 'Project_392' 'Project_393' 'Project_398'
 'Project_406' 'Project_408' 'Project_409' 'Project_416' 'Project_419'
 'Project_420' 'Project_425' 'Project_429' 'Project_438' 'Project_440'
 'Project_450' 'Project_451' 'Project_459' 'Project_461' 'Project_462'
 'Project_468' 'Project_478' 'Project_479' 'Project_62' 'Project_64'
 'Project_118' 'Project_131' 'Project_148' 'Project_172' 'Project_179'
 'Project_190' 'Project_218' 'Project_247' 'Project_252' 'Project_267'
 'Project_271' 'Project_279' 'Project_312' 'Project_324' 'Project_369'
 'Project_400' 'Project_435' 'Project_473' 'Project_39' 'Project_53'
 'Project_162' 'Project_207' 'Project_307' 'Project_313' 'Project_353'
 'Project_482' 'Project_489' 'Project_24' 'Project_199' 'Project_273'
 'Project_283' 'Project_410' 'Project_412' 'Project_288']

🔹 Developer_Name
['rmz' 'puravankara' 'tata housing' 'embassy' 'snn raj' 'prestige'
 'total environment' 'godrej' 'brigade' 'lt realty' 'sobha']

🔹 Transaction_Type
['Primary' 'Secondary']

🔹 Buyer_Type
['nri' 'other' 'high net worth' 'executive' 'entrepreneur']

🔹 Possession_Status
['Launch' 'Under construction' 'Ready to move']

🔹 Sales_Channel
['Broker' 'NRI Desk' 'Direct' 'Online']

🔹 NRI_Buyer
['yes' 'no']

🔹 Booking_Status
['Booked' 'Not Booked']

In [125]:
df['Transaction_Type'] = df['Transaction_Type'].str.lower()

In [126]:
df['Possession_Status'] = df['Possession_Status'].str.lower()

In [127]:
df['Sales_Channel'] = df['Sales_Channel'].str.lower()

In [128]:
df.to_csv("cleaned_real_estate_data.csv", index=False, encoding='utf-8')

In [129]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 45649 entries, 0 to 63716
Data columns (total 22 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Property_ID           45649 non-null  object
 1   Micro_Market          45649 non-null  object
 2   Project_Name          45649 non-null  object
 3   Developer_Name        45649 non-null  object
 4   Unit_Size_Sqft        45649 non-null  float64
 5   Ticket_Price_Cr       45649 non-null  float64
 6   Transaction_Type      45649 non-null  object
 7   Buyer_Type            45649 non-null  object
 8   Purchase_Quarter      45649 non-null  datetime64[ns]
 9   Connectivity_Score    45649 non-null  float64
 10  Amenity_Score         45649 non-null  float64
 11  Possession_Status     45649 non-null  object
 12  Sales_Channel         45649 non-null  object
 13  NRI_Buyer             45649 non-null  object
 14  Locality_Infra_Score  45649 non-null  float64
 15  Avg_Traffic_Time_Min  45649 non-null  float64
 16  Quarter_Number        45649 non-null  int32
 17  BHK                   45649 non-null  int64
 18  Price_per_Sqft        45649 non-null  float64
 19  Booking_Flag          45649 non-null  int64
 20  Booking_Status        45649 non-null  object
 21  Price_per_Sqft_Log    45649 non-null  float64
dtypes: datetime64[ns](1), float64(8), int32(1), int64(2), object(10)
memory usage: 7.8+ MB

In [130]:
df=df.drop(columns=['Price_per_Sqft_Log'])

In [131]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 45649 entries, 0 to 63716
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Property_ID           45649 non-null  object
 1   Micro_Market          45649 non-null  object
 2   Project_Name          45649 non-null  object
 3   Developer_Name        45649 non-null  object
 4   Unit_Size_Sqft        45649 non-null  float64
 5   Ticket_Price_Cr       45649 non-null  float64
 6   Transaction_Type      45649 non-null  object
 7   Buyer_Type            45649 non-null  object
 8   Purchase_Quarter      45649 non-null  datetime64[ns]
 9   Connectivity_Score    45649 non-null  float64
 10  Amenity_Score         45649 non-null  float64
 11  Possession_Status     45649 non-null  object
 12  Sales_Channel         45649 non-null  object
 13  NRI_Buyer             45649 non-null  object
 14  Locality_Infra_Score  45649 non-null  float64
 15  Avg_Traffic_Time_Min  45649 non-null  float64
 16  Quarter_Number        45649 non-null  int32
 17  BHK                   45649 non-null  int64
 18  Price_per_Sqft        45649 non-null  float64
 19  Booking_Flag          45649 non-null  int64
 20  Booking_Status        45649 non-null  object
dtypes: datetime64[ns](1), float64(7), int32(1), int64(2), object(10)
memory usage: 7.5+ MB

In [133]:
df.to_csv("cleaned_real_estate_data.csv", index=False, encoding='utf-8')